#!/usr/bin/env perl

use strict;
use warnings;
use feature 'say';

sub usage {
    say "What is it : Linux file permissions explainer";
    say "Usage      : rights PERMISSIONS";
    say "";
    say "Arguments:";
    say "  PERMISSIONS  File permissions in various formats:";
    say "               Symbolic : rwxr-xr-x, rw-------, r-x--x--x";
    say "               Numeric  : 755, 644, 777, 600, 444";
    say "";
    say "Examples:";
    say "  rights 755        Explain what 755 means";
    say "  rights rwxr-xr-x  Explain symbolic permissions";
}

sub symbolic_symbolic_perm {
    my ($perm) = @_;
    my $type   = $perm->{type} // '-';
    my $own_r  = $perm->{own_r};
    my $own_w  = $perm->{own_w};
    my $own_x  = $perm->{own_x};
    my $grp_r  = $perm->{grp_r};
    my $grp_w  = $perm->{grp_w};
    my $grp_x  = $perm->{grp_x};
    my $oth_r  = $perm->{oth_r};
    my $oth_w  = $perm->{oth_w};
    my $oth_x  = $perm->{oth_x};
    my $suffix = $perm->{suffix} // '';
}

sub explain_numeric_perm {

}

sub explain {
    my ($arg) = @_;
    if ($arg =~ /^[0-7]{3,4}$/) {
        explain_numeric_perm($arg);
    } elsif ($arg =~ /^([-dlscbp]?)([r-])([w-])([xsS-])([r-])([w-])([xsS-])([r-])([w-])([xtT-])([+\.]?)$/) {
        explain_symbolic_perm({
            type  => $1,
            own_r => $2, own_w => $3, own_x => $4,
            grp_r => $5, grp_w => $6, grp_x => $7,
            oth_r => $8, oth_w => $9, oth_x => $10,
            suffix => $11
        });
    } else {
        say "ERROR: Incorrect arg format";
        usage();
        exit 1;
    }
}

sub main {
    explain($_) for @ARGV;
    exit 0;
}

unless (@ARGV) {
    usage();
    exit 1;
}

main();
