#!/usr/bin/env perl

use strict;
use warnings;
use feature qw\say switch\;

sub check_command {
    my ($cmd) = @_;
    my @paths = split(':', $ENV{PATH} || '/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin');
    foreach my $path (@paths) {
        my $full_path = "$path/$cmd";
        return $full_path if -x $full_path;
    }
    return;
}

sub usage {
    say "What is it : Linux file permissions explainer";
    say "Usage      : rights ARGUMENTS";
    say "";
    say "Arguments:";
    say "  Symbolic permissions : rwxr-xr-x, rw-------, r-x--x--x";
    say "  Numeric permissions  : 755, 644, 777, 600, 444";
    say "  File/directory path  : /dev/video0, script.sh, /tmp";
    say "";
    say "Examples:";
    say "  rights 755           # Explain numeric permissions";
    say "  rights rwxr-xr-x     # Explain symbolic permissions";
    say "  rights /dev/video0   # Show file permissions";
}

sub explain_symbolic_perm {
    my ($perm) = @_;
    my $type   = $perm->{type} // '-';
    my $own_r  = $perm->{own_r};
    my $own_w  = $perm->{own_w};
    my $own_x  = $perm->{own_x};
    my $grp_r  = $perm->{grp_r};
    my $grp_w  = $perm->{grp_w};
    my $grp_x  = $perm->{grp_x};
    my $oth_r  = $perm->{oth_r};
    my $oth_w  = $perm->{oth_w};
    my $oth_x  = $perm->{oth_x};
    my $suffix = $perm->{suffix} // '';

    print "File type:           ";
    given ($type) {
        when ('-') { say "regular file" }
        when ('d') { say "directory" }
        when ('l') { say "symbolic link" }
        when ('p') { say "named pipe" }
        when ('c') { say "character device" }
        when ('b') { say "block device" }
        when ('s') { say "socket" }
        when ('')  { say "not specified" }
    }

    print "Owner permissions:   ";
    given ($own_r) {
        when ('r') { print "read, " }
        when ('-') { print "no read, " }
    }
    given ($own_w) {
        when ('w') { print "write, " }
        when ('-') { print "no write, " }
    }
    given ($own_x) {
        when ('x') { say "execute" }
        when ('s') { say "execute with suid (run as file owner)" }
        when ('S') { say "suid (run as file owner) set but no execute" }
        when ('-') { say "no execute" }
    }

    print "Group permissions:   ";
    given ($grp_r) {
        when ('r') { print "read, " }
        when ('-') { print "no read, " }
    }
    given ($grp_w) {
        when ('w') { print "write, " }
        when ('-') { print "no write, " }
    }
    given ($grp_x) {
        when ('x') { say "execute" }
        when ('s') { say "execute with sgid (run as group member)" }
        when ('S') { say "sgid (run as group member) set but no execute" }
        when ('-') { say "no execute" }
    }

    print "Others permissions:  ";
    given ($oth_r) {
        when ('r') { print "read, " }
        when ('-') { print "no read, " }
    }
    given ($oth_w) {
        when ('w') { print "write, " }
        when ('-') { print "no write, " }
    }
    given ($oth_x) {
        when ('x') { say "execute" }
        when ('t') { say "sticky bit (for directories: only owner or root can delete files)" }
        when ('T') { say "sticky bit (for directories: only owner or root can delete files) set but no execute" }
        when ('-') { say "no execute" }
    }

    print "Suffix:              ";
    given ($suffix) {
        when ('+') { say "ACL present (Access Control Lists)" }
        when ('.') { say "SELinux context present" }
        when ('')  { say "not specified" }
    }

    my $symbolic = $type.$own_r.$own_w.$own_x.$grp_r.$grp_w.$grp_x.$oth_r.$oth_w.$oth_x.$suffix;
    print "Symbolic:            $symbolic\n";
    
    print "Numeric:             ";
    my $own_num = 0;
    $own_num += 4 if $own_r eq 'r';
    $own_num += 2 if $own_w eq 'w';
    $own_num += 1 if $own_x =~ /[xs]/;
    my $grp_num = 0;
    $grp_num += 4 if $grp_r eq 'r';
    $grp_num += 2 if $grp_w eq 'w';
    $grp_num += 1 if $grp_x =~ /[xs]/;
    my $oth_num = 0;
    $oth_num += 4 if $oth_r eq 'r';
    $oth_num += 2 if $oth_w eq 'w';
    $oth_num += 1 if $oth_x =~ /[xt]/;
    my $special = 0;
    $special += 4 if $own_x =~ /[sS]/;
    $special += 2 if $grp_x =~ /[sS]/;
    $special += 1 if $oth_x =~ /[tT]/;
    if ($special > 0) {
        printf "%d%d%d%d\n", $special, $own_num, $grp_num, $oth_num;
    } else {
        printf "%d%d%d\n", $own_num, $grp_num, $oth_num;
    }
}

sub explain_numeric_perm {
    my ($num) = @_;
    my ($special, $owner, $group, $other) = (0, 0, 0, 0);

    if (length($num) == 3) {
        ($owner, $group, $other) = split //, $num;
    } elsif (length($num) == 4) {
        ($special, $owner, $group, $other) = split //, $num;
    }

    my %perm = (
        type   => '',
        own_r  => ($owner & 4) ? 'r' : '-',
        own_w  => ($owner & 2) ? 'w' : '-',
        own_x  => do {
            if ($owner & 1) {
                ($special & 4) ? 's' : 'x';
            } else {
                ($special & 4) ? 'S' : '-';
            }
        },
        grp_r  => ($group & 4) ? 'r' : '-',
        grp_w  => ($group & 2) ? 'w' : '-',
        grp_x  => do {
            if ($group & 1) {
                ($special & 2) ? 's' : 'x';
            } else {
                ($special & 2) ? 'S' : '-';
            }
        },
        oth_r  => ($other & 4) ? 'r' : '-',
        oth_w  => ($other & 2) ? 'w' : '-',
        oth_x  => do {
            if ($other & 1) {
                ($special & 1) ? 't' : 'x';
            } else {
                ($special & 1) ? 'T' : '-';
            }
        },
        suffix => '',
    );

    explain_symbolic_perm(\%perm);
}

sub parse_perm_string {
    my ($perm_string) = @_;
    
    if ($perm_string =~ /^([-dlscbp]?)([r-])([w-])([xsS-])([r-])([w-])([xsS-])([r-])([w-])([xtT-])([+\.]?)$/) {
        return {
            type  => $1,
            own_r => $2, own_w => $3, own_x => $4,
            grp_r => $5, grp_w => $6, grp_x => $7,
            oth_r => $8, oth_w => $9, oth_x => $10,
            suffix => $11
        };
    }
    return undef;
}

sub explain {
    my ($arg) = @_;

    if (-e $arg) {
        my $ls  = check_command('ls');
        unless ($ls) {
            say "ERROR: program 'ls' need for check file rights";
            exit 1;
        }
        
        my $perm_string = `ls -ld "$arg"`;
        chomp $perm_string;
        $perm_string =~ s/\s.*$//;
        
        my $perm = parse_perm_string($perm_string);
        if ($perm) {
            explain_symbolic_perm($perm);
        } else {
            say "ERROR: Cannot parse permissions for $arg";
            exit 1;
        }
    }
    elsif ($arg =~ /^[0-7]{3,4}$/) {
        explain_numeric_perm($arg);
    }
    else {
        my $perm = parse_perm_string($arg);
        if ($perm) {
            explain_symbolic_perm($perm);
        } else {
            say "ERROR: Incorrect permissions format";
            usage();
            exit 1;
        }
    }
}

sub main {
    for my $i (0..$#ARGV) {
        explain($ARGV[$i]);
        say "" if $i < $#ARGV;
    }
    exit 0;
}

unless (@ARGV) {
    usage();
    exit 1;
}

main();
